// 由 scripts/gen-themes.mjs 从 scripts/codex-theme-extract/core-palette.json 生成；不要手工编辑。
use super::*;
#[rustfmt::skip]
/// 随包 Codex 内置主题：完整展开配色（&'static str，满足 const 静态表）。
/// 运行时由 codex_builtin_themes 转换为 ReadRayThemeV1。
pub(crate) const CODEX_BUILTIN_FULL_THEMES: &[(CodexThemeManifest, Option<CodexThemeFullColors>, Option<CodexThemeFullColors>)] = &[
    (
        CodexThemeManifest {
            id: "catppuccin",
            name: "Catppuccin",
            version: "1.0.0",
            author: "Catppuccin",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/catppuccin/catppuccin"),
        },
        Some(CodexThemeFullColors {
            canvas: "#1e1e2e",
            sidebar: "#181825",
            surface: "#1e1e2e",
            surface_elevated: "#272736",
            surface_subtle: "#232434",
            surface_contrast: "#2c2d3e",
            text_primary: "#cdd6f4",
            text_secondary: "#bcc4e0",
            text_muted: "#7e839b",
            text_subtle: "#64687d",
            border: "#303042",
            border_soft: "#29293a",
            accent: "#cba6f7",
            accent_hover: "#cba6f7",
            accent_text: "#1a1a18",
            success: "#a6e3a1",
            success_soft: "#2d343b",
            warning: "#cba6f7",
            warning_soft: "#312d44",
            warning_strong: "#cba6f7",
            danger: "#f38ba8",
            danger_soft: "#312839",
            danger_strong: "#f38ba8",
            selection: "#3b3d4f",
            diff_added: "#a6e3a1",
            diff_removed: "#f38ba8",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#303042",
        }),
        Some(CodexThemeFullColors {
            canvas: "#eff1f5",
            sidebar: "#e6e9ef",
            surface: "#eff1f5",
            surface_elevated: "#f0f2f5",
            surface_subtle: "#eaecf1",
            surface_contrast: "#e2e4ea",
            text_primary: "#4c4f69",
            text_secondary: "#5c5f77",
            text_muted: "#9598a8",
            text_subtle: "#aeb0bd",
            border: "#dfe1e7",
            border_soft: "#e5e7ed",
            accent: "#8839ef",
            accent_hover: "#8839ef",
            accent_text: "#fff",
            success: "#40a02b",
            success_soft: "#dce8df",
            warning: "#8839ef",
            warning_soft: "#e4ddf4",
            warning_strong: "#8839ef",
            danger: "#d20f39",
            danger_soft: "#ecdde4",
            danger_strong: "#d20f39",
            selection: "#cccfd7",
            diff_added: "#40a02b",
            diff_removed: "#d20f39",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#dfe1e7",
        }),
    ),
    (
        CodexThemeManifest {
            id: "absolutely",
            name: "Absolutely",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#2d2d2b",
            sidebar: "#373735",
            surface: "#2d2d2b",
            surface_elevated: "#353533",
            surface_subtle: "#333331",
            surface_contrast: "#3d3d3b",
            text_primary: "#f9f9f7",
            text_secondary: "#e5e5e3",
            text_muted: "#9d9d9b",
            text_subtle: "#7f7f7d",
            border: "#41413f",
            border_soft: "#393937",
            accent: "#cc7d5e",
            accent_hover: "#cc7d5e",
            accent_text: "#fff",
            success: "#cc7d5e",
            success_soft: "#3e3631",
            warning: "#cc7d5e",
            warning_soft: "#3e3631",
            warning_strong: "#cc7d5e",
            danger: "#cc7d5e",
            danger_soft: "#3b3430",
            danger_strong: "#cc7d5e",
            selection: "#403731",
            diff_added: "#cc7d5e",
            diff_removed: "#cc7d5e",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#41413f",
        }),
        Some(CodexThemeFullColors {
            canvas: "#f9f9f7",
            sidebar: "#f4f4f2",
            surface: "#f9f9f7",
            surface_elevated: "#f9f9f7",
            surface_subtle: "#f3f3f1",
            surface_contrast: "#e9e9e7",
            text_primary: "#2d2d2b",
            text_secondary: "#41413f",
            text_muted: "#898987",
            text_subtle: "#a7a7a5",
            border: "#e5e5e3",
            border_soft: "#ededeb",
            accent: "#cc7d5e",
            accent_hover: "#cc7d5e",
            accent_text: "#fff",
            success: "#cc7d5e",
            success_soft: "#f4ebe6",
            warning: "#cc7d5e",
            warning_soft: "#f4ebe6",
            warning_strong: "#cc7d5e",
            danger: "#cc7d5e",
            danger_soft: "#f5eee9",
            danger_strong: "#cc7d5e",
            selection: "#f4eae5",
            diff_added: "#cc7d5e",
            diff_removed: "#cc7d5e",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e5e5e3",
        }),
    ),
    (
        CodexThemeManifest {
            id: "codex",
            name: "Codex",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#111",
            sidebar: "#131313",
            surface: "#111",
            surface_elevated: "#1b1b1b",
            surface_subtle: "#181818",
            surface_contrast: "#242424",
            text_primary: "#fcfcfc",
            text_secondary: "#e5e5e5",
            text_muted: "#929292",
            text_subtle: "#6f6f6f",
            border: "#292929",
            border_soft: "#1f1f1f",
            accent: "#0169cc",
            accent_hover: "#0169cc",
            accent_text: "#fff",
            success: "#00a240",
            success_soft: "#0f2116",
            warning: "#b06dff",
            warning_soft: "#221b2b",
            warning_strong: "#b06dff",
            danger: "#e02e2a",
            danger_soft: "#241413",
            danger_strong: "#e02e2a",
            selection: "#0f1c27",
            diff_added: "#00a240",
            diff_removed: "#e02e2a",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#292929",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#fcfcfc",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f8f8f8",
            surface_contrast: "#ececec",
            text_primary: "#0d0d0d",
            text_secondary: "#252525",
            text_muted: "#7a7a7a",
            text_subtle: "#9e9e9e",
            border: "#e7e7e7",
            border_soft: "#f0f0f0",
            accent: "#0169cc",
            accent_hover: "#0169cc",
            accent_text: "#fff",
            success: "#00a240",
            success_soft: "#e3f5ea",
            warning: "#751ed9",
            warning_soft: "#f0e6fb",
            warning_strong: "#751ed9",
            danger: "#e02e2a",
            danger_soft: "#fcecec",
            danger_strong: "#e02e2a",
            selection: "#e1edf9",
            diff_added: "#00a240",
            diff_removed: "#e02e2a",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e7e7e7",
        }),
    ),
    (
        CodexThemeManifest {
            id: "everforest",
            name: "Everforest",
            version: "1.0.0",
            author: "Sainnhe Park",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/sainnhe/everforest"),
        },
        Some(CodexThemeFullColors {
            canvas: "#2d353b",
            sidebar: "#2d353b",
            surface: "#2d353b",
            surface_elevated: "#353d43",
            surface_subtle: "#32393e",
            surface_contrast: "#3a4144",
            text_primary: "#d3c6aa",
            text_secondary: "#c2b89f",
            text_muted: "#888578",
            text_subtle: "#6f6f67",
            border: "#3e4446",
            border_soft: "#373e42",
            accent: "#a7c080",
            accent_hover: "#a7c080",
            accent_text: "#1a1a18",
            success: "#7a8c66",
            success_soft: "#353f40",
            warning: "#d699b6",
            warning_soft: "#404049",
            warning_strong: "#d699b6",
            danger: "#a16366",
            danger_soft: "#37393f",
            danger_strong: "#a16366",
            selection: "#414b51",
            diff_added: "#7a8c66",
            diff_removed: "#a16366",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#3e4446",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fdf6e3",
            sidebar: "#fdf6e3",
            surface: "#fdf6e3",
            surface_elevated: "#fdf6e4",
            surface_subtle: "#f8f2e0",
            surface_contrast: "#f0ebda",
            text_primary: "#5c6a72",
            text_secondary: "#6c787d",
            text_muted: "#a4a9a5",
            text_subtle: "#bdbeb6",
            border: "#ede8d8",
            border_soft: "#f3eedc",
            accent: "#93b259",
            accent_hover: "#93b259",
            accent_text: "#fff",
            success: "#b7c155",
            success_soft: "#f5f0d3",
            warning: "#df69ba",
            warning_soft: "#fae6de",
            warning_strong: "#df69ba",
            danger: "#fa9188",
            danger_soft: "#fdeddb",
            danger_strong: "#fa9188",
            selection: "#efe9d5",
            diff_added: "#b7c155",
            diff_removed: "#fa9188",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#ede8d8",
        }),
    ),
    (
        CodexThemeManifest {
            id: "github",
            name: "GitHub",
            version: "1.0.0",
            author: "GitHub / Primer",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/primer/github-vscode-theme"),
        },
        Some(CodexThemeFullColors {
            canvas: "#0d1117",
            sidebar: "#010409",
            surface: "#0d1117",
            surface_elevated: "#171b20",
            surface_subtle: "#14181e",
            surface_contrast: "#1e2329",
            text_primary: "#e6edf3",
            text_secondary: "#d0d7dd",
            text_muted: "#848a90",
            text_subtle: "#64696f",
            border: "#23272d",
            border_soft: "#1a1e24",
            accent: "#1f6feb",
            accent_hover: "#1f6feb",
            accent_text: "#fff",
            success: "#3fb950",
            success_soft: "#13231d",
            warning: "#bc8cff",
            warning_soft: "#201f31",
            warning_strong: "#bc8cff",
            danger: "#f85149",
            danger_soft: "#22171c",
            danger_strong: "#f85149",
            selection: "#0f1c30",
            diff_added: "#3fb950",
            diff_removed: "#f85149",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#23272d",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#f6f8fa",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f8f8f9",
            surface_contrast: "#ededee",
            text_primary: "#1f2328",
            text_secondary: "#35393d",
            text_muted: "#848689",
            text_subtle: "#a5a7a9",
            border: "#e9e9ea",
            border_soft: "#f2f2f2",
            accent: "#0969da",
            accent_hover: "#0969da",
            accent_text: "#fff",
            success: "#1a7f37",
            success_soft: "#e6f1e9",
            warning: "#8250df",
            warning_soft: "#f1ecfb",
            warning_strong: "#8250df",
            danger: "#cf222e",
            danger_soft: "#fbebec",
            danger_strong: "#cf222e",
            selection: "#e1edfb",
            diff_added: "#1a7f37",
            diff_removed: "#cf222e",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e9e9ea",
        }),
    ),
    (
        CodexThemeManifest {
            id: "gruvbox",
            name: "Gruvbox",
            version: "1.0.0",
            author: "morhetz / Gruvbox",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/morhetz/gruvbox"),
        },
        Some(CodexThemeFullColors {
            canvas: "#282828",
            sidebar: "#282828",
            surface: "#282828",
            surface_elevated: "#313131",
            surface_subtle: "#2e2d2c",
            surface_contrast: "#383633",
            text_primary: "#ebdbb2",
            text_secondary: "#d8c9a4",
            text_muted: "#938a74",
            text_subtle: "#76705f",
            border: "#3c3a36",
            border_soft: "#343330",
            accent: "#458588",
            accent_hover: "#458588",
            accent_text: "#fff",
            success: "#ebdbb2",
            success_soft: "#3d3c37",
            warning: "#b16286",
            warning_soft: "#372e32",
            warning_strong: "#b16286",
            danger: "#cc241d",
            danger_soft: "#372827",
            danger_strong: "#cc241d",
            selection: "#384539",
            diff_added: "#ebdbb2",
            diff_removed: "#cc241d",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#3c3a36",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fbf1c7",
            sidebar: "#fbf1c7",
            surface: "#fbf1c7",
            surface_elevated: "#fbf2c9",
            surface_subtle: "#f5ebc3",
            surface_contrast: "#ece2bb",
            text_primary: "#3c3836",
            text_secondary: "#4f4b45",
            text_muted: "#928b77",
            text_subtle: "#afa78d",
            border: "#e8dfb9",
            border_soft: "#f0e6be",
            accent: "#458588",
            accent_hover: "#458588",
            accent_text: "#fff",
            success: "#3c3836",
            success_soft: "#e6ddb7",
            warning: "#b16286",
            warning_soft: "#f3e1c0",
            warning_strong: "#b16286",
            danger: "#cc241d",
            danger_soft: "#f7dfb8",
            danger_strong: "#cc241d",
            selection: "#d6dcb0",
            diff_added: "#3c3836",
            diff_removed: "#cc241d",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e8dfb9",
        }),
    ),
    (
        CodexThemeManifest {
            id: "linear",
            name: "Linear",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#17181d",
            sidebar: "#080a0f",
            surface: "#17181d",
            surface_elevated: "#202126",
            surface_subtle: "#1d1e23",
            surface_contrast: "#28292e",
            text_primary: "#e6e9ef",
            text_secondary: "#d1d4da",
            text_muted: "#898b91",
            text_subtle: "#6a6c71",
            border: "#2c2d32",
            border_soft: "#23252a",
            accent: "#5e6ad2",
            accent_hover: "#5e6ad2",
            accent_text: "#fff",
            success: "#5e6ad2",
            success_soft: "#1f2131",
            warning: "#5e6ad2",
            warning_soft: "#1f2131",
            warning_strong: "#5e6ad2",
            danger: "#5e6ad2",
            danger_soft: "#1d1f2d",
            danger_strong: "#5e6ad2",
            selection: "#202233",
            diff_added: "#5e6ad2",
            diff_removed: "#5e6ad2",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#2c2d32",
        }),
        Some(CodexThemeFullColors {
            canvas: "#f7f8fa",
            sidebar: "#f2f4f8",
            surface: "#f7f8fa",
            surface_elevated: "#f7f8fa",
            surface_subtle: "#f1f2f4",
            surface_contrast: "#e7e8eb",
            text_primary: "#2a3140",
            text_secondary: "#3f4553",
            text_muted: "#868b94",
            text_subtle: "#a5a8b0",
            border: "#e3e4e7",
            border_soft: "#ebecef",
            accent: "#5e6ad2",
            accent_hover: "#5e6ad2",
            accent_text: "#fff",
            success: "#5e6ad2",
            success_soft: "#e6e8f6",
            warning: "#5e6ad2",
            warning_soft: "#e6e8f6",
            warning_strong: "#5e6ad2",
            danger: "#5e6ad2",
            danger_soft: "#e9ebf6",
            danger_strong: "#5e6ad2",
            selection: "#e5e7f5",
            diff_added: "#5e6ad2",
            diff_removed: "#5e6ad2",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e3e4e7",
        }),
    ),
    (
        CodexThemeManifest {
            id: "notion",
            name: "Notion",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#191919",
            sidebar: "#151515",
            surface: "#191919",
            surface_elevated: "#222",
            surface_subtle: "#1f1f1f",
            surface_contrast: "#282828",
            text_primary: "#d9d9d8",
            text_secondary: "#c6c6c5",
            text_muted: "#838382",
            text_subtle: "#666665",
            border: "#2c2c2c",
            border_soft: "#252524",
            accent: "#3183d8",
            accent_hover: "#3183d8",
            accent_text: "#fff",
            success: "#3183d8",
            success_soft: "#1c252e",
            warning: "#3183d8",
            warning_soft: "#1c252e",
            warning_strong: "#3183d8",
            danger: "#3183d8",
            danger_soft: "#1b232a",
            danger_strong: "#3183d8",
            selection: "#1c2630",
            diff_added: "#3183d8",
            diff_removed: "#3183d8",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#2c2c2c",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#f7f6f3",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f9f9f9",
            surface_contrast: "#efefee",
            text_primary: "#37352f",
            text_secondary: "#4b4944",
            text_muted: "#91908d",
            text_subtle: "#afaeac",
            border: "#ebebea",
            border_soft: "#f3f3f3",
            accent: "#3183d8",
            accent_hover: "#3183d8",
            accent_text: "#fff",
            success: "#3183d8",
            success_soft: "#e8f1fb",
            warning: "#3183d8",
            warning_soft: "#e8f1fb",
            warning_strong: "#3183d8",
            danger: "#3183d8",
            danger_soft: "#ecf4fb",
            danger_strong: "#3183d8",
            selection: "#e6f0fa",
            diff_added: "#3183d8",
            diff_removed: "#3183d8",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#ebebea",
        }),
    ),
    (
        CodexThemeManifest {
            id: "one",
            name: "One",
            version: "1.0.0",
            author: "akamud / One",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/akamud/vscode-theme-onedark"),
        },
        Some(CodexThemeFullColors {
            canvas: "#282c34",
            sidebar: "#21252b",
            surface: "#282c34",
            surface_elevated: "#31343c",
            surface_subtle: "#2c3038",
            surface_contrast: "#32373f",
            text_primary: "#abb2bf",
            text_secondary: "#9ea5b1",
            text_muted: "#707680",
            text_subtle: "#5c626c",
            border: "#353942",
            border_soft: "#30343c",
            accent: "#4d78cc",
            accent_hover: "#4d78cc",
            accent_text: "#fff",
            success: "#8cc265",
            success_soft: "#333d39",
            warning: "#c162de",
            warning_soft: "#393247",
            warning_strong: "#c162de",
            danger: "#e05561",
            danger_soft: "#393038",
            danger_strong: "#e05561",
            selection: "#404859",
            diff_added: "#8cc265",
            diff_removed: "#e05561",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#353942",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fafafa",
            sidebar: "#eaeaeb",
            surface: "#fafafa",
            surface_elevated: "#fafafa",
            surface_subtle: "#f4f4f4",
            surface_contrast: "#eaebeb",
            text_primary: "#383a42",
            text_secondary: "#4b4d54",
            text_muted: "#8f9095",
            text_subtle: "#acadb0",
            border: "#e7e7e8",
            border_soft: "#eeeeef",
            accent: "#526fff",
            accent_hover: "#526fff",
            accent_text: "#fff",
            success: "#526fff",
            success_soft: "#e8ebfb",
            warning: "#526fff",
            warning_soft: "#e8ebfb",
            warning_strong: "#526fff",
            danger: "#526fff",
            danger_soft: "#ebedfa",
            danger_strong: "#526fff",
            selection: "#e5e5e6",
            diff_added: "#526fff",
            diff_removed: "#526fff",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e7e7e8",
        }),
    ),
    (
        CodexThemeManifest {
            id: "raycast",
            name: "Raycast",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#141414",
            sidebar: "#101010",
            surface: "#141414",
            surface_elevated: "#1d1d1d",
            surface_subtle: "#1b1b1b",
            surface_contrast: "#272727",
            text_primary: "#fff",
            text_secondary: "#e8e8e8",
            text_muted: "#959595",
            text_subtle: "#727272",
            border: "#2c2c2c",
            border_soft: "#222",
            accent: "#4fa3f8",
            accent_hover: "#4fa3f8",
            accent_text: "#fff",
            success: "#59d499",
            success_soft: "#1c2923",
            warning: "#cf2f98",
            warning_soft: "#291723",
            warning_strong: "#cf2f98",
            danger: "#ff6363",
            danger_soft: "#291b1b",
            danger_strong: "#ff6363",
            selection: "#323232",
            diff_added: "#59d499",
            diff_removed: "#ff6363",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#2c2c2c",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#fcfcfc",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f7f7f7",
            surface_contrast: "#ebebeb",
            text_primary: "#000",
            text_secondary: "#191919",
            text_muted: "#737373",
            text_subtle: "#999",
            border: "#e6e6e6",
            border_soft: "#f0f0f0",
            accent: "#138af2",
            accent_hover: "#138af2",
            accent_text: "#fff",
            success: "#006b4f",
            success_soft: "#e3efec",
            warning: "#9a1b6e",
            warning_soft: "#f4e6ef",
            warning_strong: "#9a1b6e",
            danger: "#b12424",
            danger_soft: "#f8ebeb",
            danger_strong: "#b12424",
            selection: "#fdfdfd",
            diff_added: "#006b4f",
            diff_removed: "#b12424",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e6e6e6",
        }),
    ),
    (
        CodexThemeManifest {
            id: "rose-pine",
            name: "Rose Pine",
            version: "1.0.0",
            author: "Rose Pine",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/rose-pine/rose-pine-theme"),
        },
        Some(CodexThemeFullColors {
            canvas: "#232136",
            sidebar: "#232136",
            surface: "#232136",
            surface_elevated: "#2c2a3e",
            surface_subtle: "#29273c",
            surface_contrast: "#323045",
            text_primary: "#e0def4",
            text_secondary: "#cdcbe1",
            text_muted: "#8b899f",
            text_subtle: "#6f6d82",
            border: "#363449",
            border_soft: "#2e2c41",
            accent: "#ea9a97",
            accent_hover: "#ea9a97",
            accent_text: "#1a1a18",
            success: "#9ccfd8",
            success_soft: "#303448",
            warning: "#c4a7e7",
            warning_soft: "#353049",
            warning_strong: "#c4a7e7",
            danger: "#908caa",
            danger_soft: "#2d2b40",
            danger_strong: "#908caa",
            selection: "#312f45",
            diff_added: "#9ccfd8",
            diff_removed: "#908caa",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#363449",
        }),
        Some(CodexThemeFullColors {
            canvas: "#faf4ed",
            sidebar: "#faf4ed",
            surface: "#faf4ed",
            surface_elevated: "#faf4ee",
            surface_subtle: "#f5efea",
            surface_contrast: "#ede7e4",
            text_primary: "#575279",
            text_secondary: "#676285",
            text_muted: "#a09bad",
            text_subtle: "#b9b3bf",
            border: "#eae4e1",
            border_soft: "#f0eae6",
            accent: "#d7827e",
            accent_hover: "#d7827e",
            accent_text: "#fff",
            success: "#56949f",
            success_soft: "#e8e9e4",
            warning: "#907aa9",
            warning_soft: "#eee7e6",
            warning_strong: "#907aa9",
            danger: "#797593",
            danger_soft: "#eee9e5",
            danger_strong: "#797593",
            selection: "#efe9e5",
            diff_added: "#56949f",
            diff_removed: "#797593",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#eae4e1",
        }),
    ),
    (
        CodexThemeManifest {
            id: "solarized",
            name: "Solarized",
            version: "1.0.0",
            author: "Ethan Schoonover",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/microsoft/vscode"),
        },
        Some(CodexThemeFullColors {
            canvas: "#002b36",
            sidebar: "#00212b",
            surface: "#002b36",
            surface_elevated: "#0a333e",
            surface_subtle: "#042e39",
            surface_contrast: "#0a333e",
            text_primary: "#839496",
            text_secondary: "#768a8c",
            text_muted: "#48656b",
            text_subtle: "#34555c",
            border: "#0d3640",
            border_soft: "#08313c",
            accent: "#d30102",
            accent_hover: "#d30102",
            accent_text: "#fff",
            success: "#859900",
            success_soft: "#0f3730",
            warning: "#d33682",
            warning_soft: "#172c3e",
            warning_strong: "#d33682",
            danger: "#dc322f",
            danger_soft: "#142c35",
            danger_strong: "#dc322f",
            selection: "#274642",
            diff_added: "#859900",
            diff_removed: "#dc322f",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#0d3640",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fdf6e3",
            sidebar: "#fdf6e3",
            surface: "#fdf6e3",
            surface_elevated: "#fdf6e4",
            surface_subtle: "#f8f2e0",
            surface_contrast: "#f0ebda",
            text_primary: "#586e75",
            text_secondary: "#697c80",
            text_muted: "#a2aba7",
            text_subtle: "#bbc0b7",
            border: "#ede8d8",
            border_soft: "#f3eedc",
            accent: "#b58900",
            accent_hover: "#b58900",
            accent_text: "#fff",
            success: "#859900",
            success_soft: "#f0ecca",
            warning: "#d33682",
            warning_soft: "#f8e1d8",
            warning_strong: "#d33682",
            danger: "#dc322f",
            danger_soft: "#fae4d3",
            danger_strong: "#dc322f",
            selection: "#eee8d5",
            diff_added: "#859900",
            diff_removed: "#dc322f",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#ede8d8",
        }),
    ),
    (
        CodexThemeManifest {
            id: "vercel",
            name: "Vercel",
            version: "1.0.0",
            author: "OpenAI",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("OpenAI Codex 内置"),
            source_url: Some("https://openai.com/codex"),
        },
        Some(CodexThemeFullColors {
            canvas: "#000",
            sidebar: "#000",
            surface: "#000",
            surface_elevated: "#0a0a0a",
            surface_subtle: "#070707",
            surface_contrast: "#131313",
            text_primary: "#ededed",
            text_secondary: "#d5d5d5",
            text_muted: "#828282",
            text_subtle: "#5f5f5f",
            border: "#181818",
            border_soft: "#0e0e0e",
            accent: "#006efe",
            accent_hover: "#006efe",
            accent_text: "#fff",
            success: "#006efe",
            success_soft: "#000c1c",
            warning: "#006efe",
            warning_soft: "#000c1c",
            warning_strong: "#006efe",
            danger: "#006efe",
            danger_soft: "#000a17",
            danger_strong: "#006efe",
            selection: "#000d1e",
            diff_added: "#006efe",
            diff_removed: "#006efe",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#181818",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#fff",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f8f8f8",
            surface_contrast: "#ececec",
            text_primary: "#171717",
            text_secondary: "#2e2e2e",
            text_muted: "#7f7f7f",
            text_subtle: "#a2a2a2",
            border: "#e8e8e8",
            border_soft: "#f1f1f1",
            accent: "#006aff",
            accent_hover: "#006aff",
            accent_text: "#fff",
            success: "#006aff",
            success_soft: "#e3efff",
            warning: "#006aff",
            warning_soft: "#e3efff",
            warning_strong: "#006aff",
            danger: "#006aff",
            danger_soft: "#e8f2ff",
            danger_strong: "#006aff",
            selection: "#e0edff",
            diff_added: "#006aff",
            diff_removed: "#006aff",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e8e8e8",
        }),
    ),
    (
        CodexThemeManifest {
            id: "vscode-plus",
            name: "VS Code Plus",
            version: "1.0.0",
            author: "Microsoft (VS Code 内置)",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/microsoft/vscode"),
        },
        Some(CodexThemeFullColors {
            canvas: "#1e1e1e",
            sidebar: "#1e1e1e",
            surface: "#1e1e1e",
            surface_elevated: "#272727",
            surface_subtle: "#232323",
            surface_contrast: "#2d2d2d",
            text_primary: "#d4d4d4",
            text_secondary: "#c2c2c2",
            text_muted: "#828282",
            text_subtle: "#676767",
            border: "#303030",
            border_soft: "#292929",
            accent: "#007acc",
            accent_hover: "#007acc",
            accent_text: "#fff",
            success: "#007acc",
            success_soft: "#1b2831",
            warning: "#007acc",
            warning_soft: "#1b2831",
            warning_strong: "#007acc",
            danger: "#007acc",
            danger_soft: "#1b262e",
            danger_strong: "#007acc",
            selection: "#1a2933",
            diff_added: "#007acc",
            diff_removed: "#007acc",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#303030",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#fff",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f7f7f7",
            surface_contrast: "#ebebeb",
            text_primary: "#000",
            text_secondary: "#191919",
            text_muted: "#737373",
            text_subtle: "#999",
            border: "#e6e6e6",
            border_soft: "#f0f0f0",
            accent: "#007acc",
            accent_hover: "#007acc",
            accent_text: "#fff",
            success: "#007acc",
            success_soft: "#e3f0f9",
            warning: "#007acc",
            warning_soft: "#e3f0f9",
            warning_strong: "#007acc",
            danger: "#007acc",
            danger_soft: "#e8f3fa",
            danger_strong: "#007acc",
            selection: "#e0eff9",
            diff_added: "#007acc",
            diff_removed: "#007acc",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e6e6e6",
        }),
    ),
    (
        CodexThemeManifest {
            id: "xcode",
            name: "Xcode",
            version: "1.0.0",
            author: "Matt DeBoer",
            modes: &[ThemeMode::Dark, ThemeMode::Light],
            license: Some("MIT"),
            source_url: Some("https://github.com/matt-deboer/xcode"),
        },
        Some(CodexThemeFullColors {
            canvas: "#1f1f24",
            sidebar: "#1f1f24",
            surface: "#1f1f24",
            surface_elevated: "#28282d",
            surface_subtle: "#25252a",
            surface_contrast: "#2e2e33",
            text_primary: "#dedede",
            text_secondary: "#cbcbcc",
            text_muted: "#88888b",
            text_subtle: "#6b6b6f",
            border: "#323237",
            border_soft: "#2a2a2f",
            accent: "#5482ff",
            accent_hover: "#5482ff",
            accent_text: "#fff",
            success: "#5482ff",
            success_soft: "#252a3c",
            warning: "#5482ff",
            warning_soft: "#252a3c",
            warning_strong: "#5482ff",
            danger: "#5482ff",
            danger_soft: "#242838",
            danger_strong: "#5482ff",
            selection: "#515b70",
            diff_added: "#5482ff",
            diff_removed: "#5482ff",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#323237",
        }),
        Some(CodexThemeFullColors {
            canvas: "#fff",
            sidebar: "#fff",
            surface: "#fff",
            surface_elevated: "#fff",
            surface_subtle: "#f8f8f8",
            surface_contrast: "#eee",
            text_primary: "#262626",
            text_secondary: "#3c3c3c",
            text_muted: "#888",
            text_subtle: "#a8a8a8",
            border: "#e9e9e9",
            border_soft: "#f2f2f2",
            accent: "#0e0eff",
            accent_hover: "#0e0eff",
            accent_text: "#fff",
            success: "#0e0eff",
            success_soft: "#e4e4ff",
            warning: "#0e0eff",
            warning_soft: "#e4e4ff",
            warning_strong: "#0e0eff",
            danger: "#0e0eff",
            danger_soft: "#e9e9ff",
            danger_strong: "#0e0eff",
            selection: "#a4cdff",
            diff_added: "#0e0eff",
            diff_removed: "#0e0eff",
            scrim: "rgba(0, 0, 0, 0.32)",
            shadow: "#e9e9e9",
        }),
    ),
];
