// 由 scripts/gen-themes.mjs 从 scripts/codex-theme-extract/core-palette.json 生成；不要手工编辑。
import type { ReadRayThemeColors, ThemeMode } from "./themeProtocol.ts";

export type CodexThemeManifest = {
  formatVersion: 1;
  id: string;
  name: string;
  version: string;
  author: string;
  modes: ThemeMode[];
  license: string;
  sourceUrl: string;
};

export type CodexThemeFull = {
  manifest: CodexThemeManifest;
  dark: ReadRayThemeColors | null;
  light: ReadRayThemeColors | null;
};

export const CODEX_BUILTIN_FULL_THEMES: CodexThemeFull[] = [
  {
    manifest: {
      formatVersion: 1,
      id: "catppuccin",
      name: "Catppuccin",
      version: "1.0.0",
      author: "Catppuccin",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/catppuccin/catppuccin",
    },
    dark:     {
      canvas: "#1e1e2e",
      sidebar: "#181825",
      surface: "#1e1e2e",
      surfaceElevated: "#272736",
      surfaceSubtle: "#232434",
      surfaceContrast: "#2c2d3e",
      textPrimary: "#cdd6f4",
      textSecondary: "#bcc4e0",
      textMuted: "#7e839b",
      textSubtle: "#64687d",
      border: "#303042",
      borderSoft: "#29293a",
      accent: "#cba6f7",
      accentHover: "#cba6f7",
      accentText: "#1a1a18",
      success: "#a6e3a1",
      successSoft: "#2d343b",
      warning: "#cba6f7",
      warningSoft: "#312d44",
      warningStrong: "#cba6f7",
      danger: "#f38ba8",
      dangerSoft: "#312839",
      dangerStrong: "#f38ba8",
      selection: "#3b3d4f",
      diffAdded: "#a6e3a1",
      diffRemoved: "#f38ba8",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#303042",
    },
    light:     {
      canvas: "#eff1f5",
      sidebar: "#e6e9ef",
      surface: "#eff1f5",
      surfaceElevated: "#f0f2f5",
      surfaceSubtle: "#eaecf1",
      surfaceContrast: "#e2e4ea",
      textPrimary: "#4c4f69",
      textSecondary: "#5c5f77",
      textMuted: "#9598a8",
      textSubtle: "#aeb0bd",
      border: "#dfe1e7",
      borderSoft: "#e5e7ed",
      accent: "#8839ef",
      accentHover: "#8839ef",
      accentText: "#fff",
      success: "#40a02b",
      successSoft: "#dce8df",
      warning: "#8839ef",
      warningSoft: "#e4ddf4",
      warningStrong: "#8839ef",
      danger: "#d20f39",
      dangerSoft: "#ecdde4",
      dangerStrong: "#d20f39",
      selection: "#cccfd7",
      diffAdded: "#40a02b",
      diffRemoved: "#d20f39",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#dfe1e7",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "absolutely",
      name: "Absolutely",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#2d2d2b",
      sidebar: "#373735",
      surface: "#2d2d2b",
      surfaceElevated: "#353533",
      surfaceSubtle: "#333331",
      surfaceContrast: "#3d3d3b",
      textPrimary: "#f9f9f7",
      textSecondary: "#e5e5e3",
      textMuted: "#9d9d9b",
      textSubtle: "#7f7f7d",
      border: "#41413f",
      borderSoft: "#393937",
      accent: "#cc7d5e",
      accentHover: "#cc7d5e",
      accentText: "#fff",
      success: "#cc7d5e",
      successSoft: "#3e3631",
      warning: "#cc7d5e",
      warningSoft: "#3e3631",
      warningStrong: "#cc7d5e",
      danger: "#cc7d5e",
      dangerSoft: "#3b3430",
      dangerStrong: "#cc7d5e",
      selection: "#403731",
      diffAdded: "#cc7d5e",
      diffRemoved: "#cc7d5e",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#41413f",
    },
    light:     {
      canvas: "#f9f9f7",
      sidebar: "#f4f4f2",
      surface: "#f9f9f7",
      surfaceElevated: "#f9f9f7",
      surfaceSubtle: "#f3f3f1",
      surfaceContrast: "#e9e9e7",
      textPrimary: "#2d2d2b",
      textSecondary: "#41413f",
      textMuted: "#898987",
      textSubtle: "#a7a7a5",
      border: "#e5e5e3",
      borderSoft: "#ededeb",
      accent: "#cc7d5e",
      accentHover: "#cc7d5e",
      accentText: "#fff",
      success: "#cc7d5e",
      successSoft: "#f4ebe6",
      warning: "#cc7d5e",
      warningSoft: "#f4ebe6",
      warningStrong: "#cc7d5e",
      danger: "#cc7d5e",
      dangerSoft: "#f5eee9",
      dangerStrong: "#cc7d5e",
      selection: "#f4eae5",
      diffAdded: "#cc7d5e",
      diffRemoved: "#cc7d5e",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e5e5e3",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "codex",
      name: "Codex",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#111",
      sidebar: "#131313",
      surface: "#111",
      surfaceElevated: "#1b1b1b",
      surfaceSubtle: "#181818",
      surfaceContrast: "#242424",
      textPrimary: "#fcfcfc",
      textSecondary: "#e5e5e5",
      textMuted: "#929292",
      textSubtle: "#6f6f6f",
      border: "#292929",
      borderSoft: "#1f1f1f",
      accent: "#0169cc",
      accentHover: "#0169cc",
      accentText: "#fff",
      success: "#00a240",
      successSoft: "#0f2116",
      warning: "#b06dff",
      warningSoft: "#221b2b",
      warningStrong: "#b06dff",
      danger: "#e02e2a",
      dangerSoft: "#241413",
      dangerStrong: "#e02e2a",
      selection: "#0f1c27",
      diffAdded: "#00a240",
      diffRemoved: "#e02e2a",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#292929",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#fcfcfc",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f8f8f8",
      surfaceContrast: "#ececec",
      textPrimary: "#0d0d0d",
      textSecondary: "#252525",
      textMuted: "#7a7a7a",
      textSubtle: "#9e9e9e",
      border: "#e7e7e7",
      borderSoft: "#f0f0f0",
      accent: "#0169cc",
      accentHover: "#0169cc",
      accentText: "#fff",
      success: "#00a240",
      successSoft: "#e3f5ea",
      warning: "#751ed9",
      warningSoft: "#f0e6fb",
      warningStrong: "#751ed9",
      danger: "#e02e2a",
      dangerSoft: "#fcecec",
      dangerStrong: "#e02e2a",
      selection: "#e1edf9",
      diffAdded: "#00a240",
      diffRemoved: "#e02e2a",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e7e7e7",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "everforest",
      name: "Everforest",
      version: "1.0.0",
      author: "Sainnhe Park",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/sainnhe/everforest",
    },
    dark:     {
      canvas: "#2d353b",
      sidebar: "#2d353b",
      surface: "#2d353b",
      surfaceElevated: "#353d43",
      surfaceSubtle: "#32393e",
      surfaceContrast: "#3a4144",
      textPrimary: "#d3c6aa",
      textSecondary: "#c2b89f",
      textMuted: "#888578",
      textSubtle: "#6f6f67",
      border: "#3e4446",
      borderSoft: "#373e42",
      accent: "#a7c080",
      accentHover: "#a7c080",
      accentText: "#1a1a18",
      success: "#7a8c66",
      successSoft: "#353f40",
      warning: "#d699b6",
      warningSoft: "#404049",
      warningStrong: "#d699b6",
      danger: "#a16366",
      dangerSoft: "#37393f",
      dangerStrong: "#a16366",
      selection: "#414b51",
      diffAdded: "#7a8c66",
      diffRemoved: "#a16366",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#3e4446",
    },
    light:     {
      canvas: "#fdf6e3",
      sidebar: "#fdf6e3",
      surface: "#fdf6e3",
      surfaceElevated: "#fdf6e4",
      surfaceSubtle: "#f8f2e0",
      surfaceContrast: "#f0ebda",
      textPrimary: "#5c6a72",
      textSecondary: "#6c787d",
      textMuted: "#a4a9a5",
      textSubtle: "#bdbeb6",
      border: "#ede8d8",
      borderSoft: "#f3eedc",
      accent: "#93b259",
      accentHover: "#93b259",
      accentText: "#fff",
      success: "#b7c155",
      successSoft: "#f5f0d3",
      warning: "#df69ba",
      warningSoft: "#fae6de",
      warningStrong: "#df69ba",
      danger: "#fa9188",
      dangerSoft: "#fdeddb",
      dangerStrong: "#fa9188",
      selection: "#efe9d5",
      diffAdded: "#b7c155",
      diffRemoved: "#fa9188",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#ede8d8",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "github",
      name: "GitHub",
      version: "1.0.0",
      author: "GitHub / Primer",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/primer/github-vscode-theme",
    },
    dark:     {
      canvas: "#0d1117",
      sidebar: "#010409",
      surface: "#0d1117",
      surfaceElevated: "#171b20",
      surfaceSubtle: "#14181e",
      surfaceContrast: "#1e2329",
      textPrimary: "#e6edf3",
      textSecondary: "#d0d7dd",
      textMuted: "#848a90",
      textSubtle: "#64696f",
      border: "#23272d",
      borderSoft: "#1a1e24",
      accent: "#1f6feb",
      accentHover: "#1f6feb",
      accentText: "#fff",
      success: "#3fb950",
      successSoft: "#13231d",
      warning: "#bc8cff",
      warningSoft: "#201f31",
      warningStrong: "#bc8cff",
      danger: "#f85149",
      dangerSoft: "#22171c",
      dangerStrong: "#f85149",
      selection: "#0f1c30",
      diffAdded: "#3fb950",
      diffRemoved: "#f85149",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#23272d",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#f6f8fa",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f8f8f9",
      surfaceContrast: "#ededee",
      textPrimary: "#1f2328",
      textSecondary: "#35393d",
      textMuted: "#848689",
      textSubtle: "#a5a7a9",
      border: "#e9e9ea",
      borderSoft: "#f2f2f2",
      accent: "#0969da",
      accentHover: "#0969da",
      accentText: "#fff",
      success: "#1a7f37",
      successSoft: "#e6f1e9",
      warning: "#8250df",
      warningSoft: "#f1ecfb",
      warningStrong: "#8250df",
      danger: "#cf222e",
      dangerSoft: "#fbebec",
      dangerStrong: "#cf222e",
      selection: "#e1edfb",
      diffAdded: "#1a7f37",
      diffRemoved: "#cf222e",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e9e9ea",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "gruvbox",
      name: "Gruvbox",
      version: "1.0.0",
      author: "morhetz / Gruvbox",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/morhetz/gruvbox",
    },
    dark:     {
      canvas: "#282828",
      sidebar: "#282828",
      surface: "#282828",
      surfaceElevated: "#313131",
      surfaceSubtle: "#2e2d2c",
      surfaceContrast: "#383633",
      textPrimary: "#ebdbb2",
      textSecondary: "#d8c9a4",
      textMuted: "#938a74",
      textSubtle: "#76705f",
      border: "#3c3a36",
      borderSoft: "#343330",
      accent: "#458588",
      accentHover: "#458588",
      accentText: "#fff",
      success: "#ebdbb2",
      successSoft: "#3d3c37",
      warning: "#b16286",
      warningSoft: "#372e32",
      warningStrong: "#b16286",
      danger: "#cc241d",
      dangerSoft: "#372827",
      dangerStrong: "#cc241d",
      selection: "#384539",
      diffAdded: "#ebdbb2",
      diffRemoved: "#cc241d",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#3c3a36",
    },
    light:     {
      canvas: "#fbf1c7",
      sidebar: "#fbf1c7",
      surface: "#fbf1c7",
      surfaceElevated: "#fbf2c9",
      surfaceSubtle: "#f5ebc3",
      surfaceContrast: "#ece2bb",
      textPrimary: "#3c3836",
      textSecondary: "#4f4b45",
      textMuted: "#928b77",
      textSubtle: "#afa78d",
      border: "#e8dfb9",
      borderSoft: "#f0e6be",
      accent: "#458588",
      accentHover: "#458588",
      accentText: "#fff",
      success: "#3c3836",
      successSoft: "#e6ddb7",
      warning: "#b16286",
      warningSoft: "#f3e1c0",
      warningStrong: "#b16286",
      danger: "#cc241d",
      dangerSoft: "#f7dfb8",
      dangerStrong: "#cc241d",
      selection: "#d6dcb0",
      diffAdded: "#3c3836",
      diffRemoved: "#cc241d",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e8dfb9",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "linear",
      name: "Linear",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#17181d",
      sidebar: "#080a0f",
      surface: "#17181d",
      surfaceElevated: "#202126",
      surfaceSubtle: "#1d1e23",
      surfaceContrast: "#28292e",
      textPrimary: "#e6e9ef",
      textSecondary: "#d1d4da",
      textMuted: "#898b91",
      textSubtle: "#6a6c71",
      border: "#2c2d32",
      borderSoft: "#23252a",
      accent: "#5e6ad2",
      accentHover: "#5e6ad2",
      accentText: "#fff",
      success: "#5e6ad2",
      successSoft: "#1f2131",
      warning: "#5e6ad2",
      warningSoft: "#1f2131",
      warningStrong: "#5e6ad2",
      danger: "#5e6ad2",
      dangerSoft: "#1d1f2d",
      dangerStrong: "#5e6ad2",
      selection: "#202233",
      diffAdded: "#5e6ad2",
      diffRemoved: "#5e6ad2",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#2c2d32",
    },
    light:     {
      canvas: "#f7f8fa",
      sidebar: "#f2f4f8",
      surface: "#f7f8fa",
      surfaceElevated: "#f7f8fa",
      surfaceSubtle: "#f1f2f4",
      surfaceContrast: "#e7e8eb",
      textPrimary: "#2a3140",
      textSecondary: "#3f4553",
      textMuted: "#868b94",
      textSubtle: "#a5a8b0",
      border: "#e3e4e7",
      borderSoft: "#ebecef",
      accent: "#5e6ad2",
      accentHover: "#5e6ad2",
      accentText: "#fff",
      success: "#5e6ad2",
      successSoft: "#e6e8f6",
      warning: "#5e6ad2",
      warningSoft: "#e6e8f6",
      warningStrong: "#5e6ad2",
      danger: "#5e6ad2",
      dangerSoft: "#e9ebf6",
      dangerStrong: "#5e6ad2",
      selection: "#e5e7f5",
      diffAdded: "#5e6ad2",
      diffRemoved: "#5e6ad2",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e3e4e7",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "notion",
      name: "Notion",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#191919",
      sidebar: "#151515",
      surface: "#191919",
      surfaceElevated: "#222",
      surfaceSubtle: "#1f1f1f",
      surfaceContrast: "#282828",
      textPrimary: "#d9d9d8",
      textSecondary: "#c6c6c5",
      textMuted: "#838382",
      textSubtle: "#666665",
      border: "#2c2c2c",
      borderSoft: "#252524",
      accent: "#3183d8",
      accentHover: "#3183d8",
      accentText: "#fff",
      success: "#3183d8",
      successSoft: "#1c252e",
      warning: "#3183d8",
      warningSoft: "#1c252e",
      warningStrong: "#3183d8",
      danger: "#3183d8",
      dangerSoft: "#1b232a",
      dangerStrong: "#3183d8",
      selection: "#1c2630",
      diffAdded: "#3183d8",
      diffRemoved: "#3183d8",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#2c2c2c",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#f7f6f3",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f9f9f9",
      surfaceContrast: "#efefee",
      textPrimary: "#37352f",
      textSecondary: "#4b4944",
      textMuted: "#91908d",
      textSubtle: "#afaeac",
      border: "#ebebea",
      borderSoft: "#f3f3f3",
      accent: "#3183d8",
      accentHover: "#3183d8",
      accentText: "#fff",
      success: "#3183d8",
      successSoft: "#e8f1fb",
      warning: "#3183d8",
      warningSoft: "#e8f1fb",
      warningStrong: "#3183d8",
      danger: "#3183d8",
      dangerSoft: "#ecf4fb",
      dangerStrong: "#3183d8",
      selection: "#e6f0fa",
      diffAdded: "#3183d8",
      diffRemoved: "#3183d8",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#ebebea",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "one",
      name: "One",
      version: "1.0.0",
      author: "akamud / One",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/akamud/vscode-theme-onedark",
    },
    dark:     {
      canvas: "#282c34",
      sidebar: "#21252b",
      surface: "#282c34",
      surfaceElevated: "#31343c",
      surfaceSubtle: "#2c3038",
      surfaceContrast: "#32373f",
      textPrimary: "#abb2bf",
      textSecondary: "#9ea5b1",
      textMuted: "#707680",
      textSubtle: "#5c626c",
      border: "#353942",
      borderSoft: "#30343c",
      accent: "#4d78cc",
      accentHover: "#4d78cc",
      accentText: "#fff",
      success: "#8cc265",
      successSoft: "#333d39",
      warning: "#c162de",
      warningSoft: "#393247",
      warningStrong: "#c162de",
      danger: "#e05561",
      dangerSoft: "#393038",
      dangerStrong: "#e05561",
      selection: "#404859",
      diffAdded: "#8cc265",
      diffRemoved: "#e05561",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#353942",
    },
    light:     {
      canvas: "#fafafa",
      sidebar: "#eaeaeb",
      surface: "#fafafa",
      surfaceElevated: "#fafafa",
      surfaceSubtle: "#f4f4f4",
      surfaceContrast: "#eaebeb",
      textPrimary: "#383a42",
      textSecondary: "#4b4d54",
      textMuted: "#8f9095",
      textSubtle: "#acadb0",
      border: "#e7e7e8",
      borderSoft: "#eeeeef",
      accent: "#526fff",
      accentHover: "#526fff",
      accentText: "#fff",
      success: "#526fff",
      successSoft: "#e8ebfb",
      warning: "#526fff",
      warningSoft: "#e8ebfb",
      warningStrong: "#526fff",
      danger: "#526fff",
      dangerSoft: "#ebedfa",
      dangerStrong: "#526fff",
      selection: "#e5e5e6",
      diffAdded: "#526fff",
      diffRemoved: "#526fff",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e7e7e8",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "raycast",
      name: "Raycast",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#141414",
      sidebar: "#101010",
      surface: "#141414",
      surfaceElevated: "#1d1d1d",
      surfaceSubtle: "#1b1b1b",
      surfaceContrast: "#272727",
      textPrimary: "#fff",
      textSecondary: "#e8e8e8",
      textMuted: "#959595",
      textSubtle: "#727272",
      border: "#2c2c2c",
      borderSoft: "#222",
      accent: "#4fa3f8",
      accentHover: "#4fa3f8",
      accentText: "#fff",
      success: "#59d499",
      successSoft: "#1c2923",
      warning: "#cf2f98",
      warningSoft: "#291723",
      warningStrong: "#cf2f98",
      danger: "#ff6363",
      dangerSoft: "#291b1b",
      dangerStrong: "#ff6363",
      selection: "#323232",
      diffAdded: "#59d499",
      diffRemoved: "#ff6363",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#2c2c2c",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#fcfcfc",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f7f7f7",
      surfaceContrast: "#ebebeb",
      textPrimary: "#000",
      textSecondary: "#191919",
      textMuted: "#737373",
      textSubtle: "#999",
      border: "#e6e6e6",
      borderSoft: "#f0f0f0",
      accent: "#138af2",
      accentHover: "#138af2",
      accentText: "#fff",
      success: "#006b4f",
      successSoft: "#e3efec",
      warning: "#9a1b6e",
      warningSoft: "#f4e6ef",
      warningStrong: "#9a1b6e",
      danger: "#b12424",
      dangerSoft: "#f8ebeb",
      dangerStrong: "#b12424",
      selection: "#fdfdfd",
      diffAdded: "#006b4f",
      diffRemoved: "#b12424",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e6e6e6",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "rose-pine",
      name: "Rose Pine",
      version: "1.0.0",
      author: "Rose Pine",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/rose-pine/rose-pine-theme",
    },
    dark:     {
      canvas: "#232136",
      sidebar: "#232136",
      surface: "#232136",
      surfaceElevated: "#2c2a3e",
      surfaceSubtle: "#29273c",
      surfaceContrast: "#323045",
      textPrimary: "#e0def4",
      textSecondary: "#cdcbe1",
      textMuted: "#8b899f",
      textSubtle: "#6f6d82",
      border: "#363449",
      borderSoft: "#2e2c41",
      accent: "#ea9a97",
      accentHover: "#ea9a97",
      accentText: "#1a1a18",
      success: "#9ccfd8",
      successSoft: "#303448",
      warning: "#c4a7e7",
      warningSoft: "#353049",
      warningStrong: "#c4a7e7",
      danger: "#908caa",
      dangerSoft: "#2d2b40",
      dangerStrong: "#908caa",
      selection: "#312f45",
      diffAdded: "#9ccfd8",
      diffRemoved: "#908caa",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#363449",
    },
    light:     {
      canvas: "#faf4ed",
      sidebar: "#faf4ed",
      surface: "#faf4ed",
      surfaceElevated: "#faf4ee",
      surfaceSubtle: "#f5efea",
      surfaceContrast: "#ede7e4",
      textPrimary: "#575279",
      textSecondary: "#676285",
      textMuted: "#a09bad",
      textSubtle: "#b9b3bf",
      border: "#eae4e1",
      borderSoft: "#f0eae6",
      accent: "#d7827e",
      accentHover: "#d7827e",
      accentText: "#fff",
      success: "#56949f",
      successSoft: "#e8e9e4",
      warning: "#907aa9",
      warningSoft: "#eee7e6",
      warningStrong: "#907aa9",
      danger: "#797593",
      dangerSoft: "#eee9e5",
      dangerStrong: "#797593",
      selection: "#efe9e5",
      diffAdded: "#56949f",
      diffRemoved: "#797593",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#eae4e1",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "solarized",
      name: "Solarized",
      version: "1.0.0",
      author: "Ethan Schoonover",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/microsoft/vscode",
    },
    dark:     {
      canvas: "#002b36",
      sidebar: "#00212b",
      surface: "#002b36",
      surfaceElevated: "#0a333e",
      surfaceSubtle: "#042e39",
      surfaceContrast: "#0a333e",
      textPrimary: "#839496",
      textSecondary: "#768a8c",
      textMuted: "#48656b",
      textSubtle: "#34555c",
      border: "#0d3640",
      borderSoft: "#08313c",
      accent: "#d30102",
      accentHover: "#d30102",
      accentText: "#fff",
      success: "#859900",
      successSoft: "#0f3730",
      warning: "#d33682",
      warningSoft: "#172c3e",
      warningStrong: "#d33682",
      danger: "#dc322f",
      dangerSoft: "#142c35",
      dangerStrong: "#dc322f",
      selection: "#274642",
      diffAdded: "#859900",
      diffRemoved: "#dc322f",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#0d3640",
    },
    light:     {
      canvas: "#fdf6e3",
      sidebar: "#fdf6e3",
      surface: "#fdf6e3",
      surfaceElevated: "#fdf6e4",
      surfaceSubtle: "#f8f2e0",
      surfaceContrast: "#f0ebda",
      textPrimary: "#586e75",
      textSecondary: "#697c80",
      textMuted: "#a2aba7",
      textSubtle: "#bbc0b7",
      border: "#ede8d8",
      borderSoft: "#f3eedc",
      accent: "#b58900",
      accentHover: "#b58900",
      accentText: "#fff",
      success: "#859900",
      successSoft: "#f0ecca",
      warning: "#d33682",
      warningSoft: "#f8e1d8",
      warningStrong: "#d33682",
      danger: "#dc322f",
      dangerSoft: "#fae4d3",
      dangerStrong: "#dc322f",
      selection: "#eee8d5",
      diffAdded: "#859900",
      diffRemoved: "#dc322f",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#ede8d8",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "vercel",
      name: "Vercel",
      version: "1.0.0",
      author: "OpenAI",
      modes: ["dark", "light"],
      license: "OpenAI Codex 内置",
      sourceUrl: "https://openai.com/codex",
    },
    dark:     {
      canvas: "#000",
      sidebar: "#000",
      surface: "#000",
      surfaceElevated: "#0a0a0a",
      surfaceSubtle: "#070707",
      surfaceContrast: "#131313",
      textPrimary: "#ededed",
      textSecondary: "#d5d5d5",
      textMuted: "#828282",
      textSubtle: "#5f5f5f",
      border: "#181818",
      borderSoft: "#0e0e0e",
      accent: "#006efe",
      accentHover: "#006efe",
      accentText: "#fff",
      success: "#006efe",
      successSoft: "#000c1c",
      warning: "#006efe",
      warningSoft: "#000c1c",
      warningStrong: "#006efe",
      danger: "#006efe",
      dangerSoft: "#000a17",
      dangerStrong: "#006efe",
      selection: "#000d1e",
      diffAdded: "#006efe",
      diffRemoved: "#006efe",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#181818",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#fff",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f8f8f8",
      surfaceContrast: "#ececec",
      textPrimary: "#171717",
      textSecondary: "#2e2e2e",
      textMuted: "#7f7f7f",
      textSubtle: "#a2a2a2",
      border: "#e8e8e8",
      borderSoft: "#f1f1f1",
      accent: "#006aff",
      accentHover: "#006aff",
      accentText: "#fff",
      success: "#006aff",
      successSoft: "#e3efff",
      warning: "#006aff",
      warningSoft: "#e3efff",
      warningStrong: "#006aff",
      danger: "#006aff",
      dangerSoft: "#e8f2ff",
      dangerStrong: "#006aff",
      selection: "#e0edff",
      diffAdded: "#006aff",
      diffRemoved: "#006aff",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e8e8e8",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "vscode-plus",
      name: "VS Code Plus",
      version: "1.0.0",
      author: "Microsoft (VS Code 内置)",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/microsoft/vscode",
    },
    dark:     {
      canvas: "#1e1e1e",
      sidebar: "#1e1e1e",
      surface: "#1e1e1e",
      surfaceElevated: "#272727",
      surfaceSubtle: "#232323",
      surfaceContrast: "#2d2d2d",
      textPrimary: "#d4d4d4",
      textSecondary: "#c2c2c2",
      textMuted: "#828282",
      textSubtle: "#676767",
      border: "#303030",
      borderSoft: "#292929",
      accent: "#007acc",
      accentHover: "#007acc",
      accentText: "#fff",
      success: "#007acc",
      successSoft: "#1b2831",
      warning: "#007acc",
      warningSoft: "#1b2831",
      warningStrong: "#007acc",
      danger: "#007acc",
      dangerSoft: "#1b262e",
      dangerStrong: "#007acc",
      selection: "#1a2933",
      diffAdded: "#007acc",
      diffRemoved: "#007acc",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#303030",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#fff",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f7f7f7",
      surfaceContrast: "#ebebeb",
      textPrimary: "#000",
      textSecondary: "#191919",
      textMuted: "#737373",
      textSubtle: "#999",
      border: "#e6e6e6",
      borderSoft: "#f0f0f0",
      accent: "#007acc",
      accentHover: "#007acc",
      accentText: "#fff",
      success: "#007acc",
      successSoft: "#e3f0f9",
      warning: "#007acc",
      warningSoft: "#e3f0f9",
      warningStrong: "#007acc",
      danger: "#007acc",
      dangerSoft: "#e8f3fa",
      dangerStrong: "#007acc",
      selection: "#e0eff9",
      diffAdded: "#007acc",
      diffRemoved: "#007acc",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e6e6e6",
    },
  },
  {
    manifest: {
      formatVersion: 1,
      id: "xcode",
      name: "Xcode",
      version: "1.0.0",
      author: "Matt DeBoer",
      modes: ["dark", "light"],
      license: "MIT",
      sourceUrl: "https://github.com/matt-deboer/xcode",
    },
    dark:     {
      canvas: "#1f1f24",
      sidebar: "#1f1f24",
      surface: "#1f1f24",
      surfaceElevated: "#28282d",
      surfaceSubtle: "#25252a",
      surfaceContrast: "#2e2e33",
      textPrimary: "#dedede",
      textSecondary: "#cbcbcc",
      textMuted: "#88888b",
      textSubtle: "#6b6b6f",
      border: "#323237",
      borderSoft: "#2a2a2f",
      accent: "#5482ff",
      accentHover: "#5482ff",
      accentText: "#fff",
      success: "#5482ff",
      successSoft: "#252a3c",
      warning: "#5482ff",
      warningSoft: "#252a3c",
      warningStrong: "#5482ff",
      danger: "#5482ff",
      dangerSoft: "#242838",
      dangerStrong: "#5482ff",
      selection: "#515b70",
      diffAdded: "#5482ff",
      diffRemoved: "#5482ff",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#323237",
    },
    light:     {
      canvas: "#fff",
      sidebar: "#fff",
      surface: "#fff",
      surfaceElevated: "#fff",
      surfaceSubtle: "#f8f8f8",
      surfaceContrast: "#eee",
      textPrimary: "#262626",
      textSecondary: "#3c3c3c",
      textMuted: "#888",
      textSubtle: "#a8a8a8",
      border: "#e9e9e9",
      borderSoft: "#f2f2f2",
      accent: "#0e0eff",
      accentHover: "#0e0eff",
      accentText: "#fff",
      success: "#0e0eff",
      successSoft: "#e4e4ff",
      warning: "#0e0eff",
      warningSoft: "#e4e4ff",
      warningStrong: "#0e0eff",
      danger: "#0e0eff",
      dangerSoft: "#e9e9ff",
      dangerStrong: "#0e0eff",
      selection: "#a4cdff",
      diffAdded: "#0e0eff",
      diffRemoved: "#0e0eff",
      scrim: "rgba(0, 0, 0, 0.32)",
      shadow: "#e9e9e9",
    },
  },
];
